### ISSUE TITLE
Sheet becomes stuck in any position in a specific condition, and how to make the offset using Safe Area?

### ISSUE THREAD

**Issue by DavinHrdy** [OfTheWolf/UBottomSheet#10]
Really love your approach in making the bottom sheet. 

I've followed your setup and I got it working but I seem to have a problem when I pan down the tableview until the sheet is dragged down in any place, then pan back up, the sheet becomes stuck until I scroll to the top of the tableview. Is there a way to fix it? (logically, a way to disable the tableview scroll during the pan gesture handling, but I still haven’t found the correct way)

The whole sheet:
![Simulator Screen Shot - iPhone SE - 2019-09-15 at 08 41 21](https://user-images.githubusercontent.com/16251308/64915585-c7e02d00-d794-11e9-8c27-1b5078a83010.png)

Described case:
![Simulator Screen Shot - iPhone SE - 2019-09-15 at 08 40 59](https://user-images.githubusercontent.com/16251308/64915590-e2b2a180-d794-11e9-90c6-3f882066c96e.png)

Storyboard:
<img width="359" alt="Screen Shot 2019-09-15 at 8 44 07 AM" src="https://user-images.githubusercontent.com/16251308/64915600-04ac2400-d795-11e9-980f-51160efe9653.png">

Maybe with this approach it is not allowed to have buttons at the bottom part?

Second question: How can I make the offset universal? Seems like the offset is determined programmatically fixed, but when I correctly set up in the iPhone X style, the bottom sheet in the iPhone 5s/SE becomes too high

**Comment by DavinHrdy** [comment]
Nevermind the second question, got it working by setting the bottomOffset using the same method for my bottom sheet constraint, using multiplier of the safe area.

**Comment by OfTheWolf** [comment]
@DavinHrdy I am changing the logic so it will be supported with the new update. It will be ready within a few days.

**Comment by OfTheWolf** [comment]
I updated the repo as a pod lib. Now it supports what you need. See Example project.
