### ISSUE TITLE
Thank you for providing a good solution.

### ISSUE THREAD

**Issue by jasudev** [OfTheWolf/UBottomSheet#11]
Thank you for providing a good solution.
But I found a serious problem.
Running without connecting with Xcode will crash.
I used the sample provided.
Running an app built without connecting with Xcode will result in a 100% crash.
Can you determine the cause of the problem?
Thank you.

**Comment by OfTheWolf** [comment]
@jasudev I am glad you liked it thanks. The problem is about MapKit framework. you must add the framework.  Open your target's General tab. click '+' under "Frameworks, Libraries, and Embedded Content" section. Add MapKit framework from the list and you are good to go.

**Comment by jasudev** [comment]
@OfTheWolf Thank you. It was a great help. :)
