### ISSUE TITLE
Quick question...

### ISSUE THREAD

**Issue by LilMoke** [OfTheWolf/UBottomSheet#13]
Is there a way to detect when the user pulls own the sheet?  I was wondering because I want to dismiss the keyboard when they close down the view.

Thanks for the help!!

**Comment by OfTheWolf** [comment]
Currently there is no support this but u can add it if you want. Go to BottomSheetController.swift and find where i set "self.topConstraint?.constant". You can put your delegate or observer right after these lines. 
For example 
`self.topConstraint?.constant = f.minY`
`self.delegate?.bottomSheetDidMove(percentage: f.minY / maxSheetHeight)`

**Comment by OfTheWolf** [comment]
See UBottomSheetCoordinatorDelegate in version 1.x.
