### ISSUE TITLE
Use CollectionView with horizontal scroll direction 

### ISSUE THREAD

**Issue by syafieqq** [OfTheWolf/UBottomSheet#14]
Hi, thanks for the awesome library.
Just one to ask, I use collection view instead of table view, it works well when it is on vertical direction.
But, when I use horizontal direction, it does not goes well, when I swap the collection view to right or left, the sheet keep move along upside and downside sometime., I have used below code, but still does not work.    

```
   override var scrollView: UIScrollView?{
        return collectionView
    }
```

Thanks.

**Comment by OfTheWolf** [comment]
Hi @syafieqq, 

Can you share view hierarchy of the sheet? e.g. UIView -> UICollectionView (Vertical) -> UICollectionViewCell etc..

**Comment by syafieqq** [comment]
Here the hierachy:
visual effect view -> view -> collection view (vertical/ horizontal) -> collection view cell -> content (UIView) -> UIImage (width = screen width, height = screen height)

I think if I drag left and right linearly, then it should be no problem.

**Comment by OfTheWolf** [comment]
I couldn't reproduce the problem. Can you share a code sample or video?

**Comment by OfTheWolf** [comment]
you can check the example with horizontal collectionView available after version 1.x.
