### ISSUE TITLE
how to change / control height of sheet?

### ISSUE THREAD

**Issue by donzai1849** [OfTheWolf/UBottomSheet#15]

**Comment by OfTheWolf** [comment]
You can override these

   ```
//1 : full height, 0 : minimum height default is 1
    open var topYPercentage: CGFloat{
        return 1
    }
    
    //1 : full height, 0 : minimum height default is 0.5
    open var middleYPercentage: CGFloat{
        return 0.5
    }
    
    //1 : full height, 0 : minimum height default is 0.1
    open var bottomYPercentage: CGFloat{
        return 0.1
    }
```

**Comment by OfTheWolf** [comment]
after version 1.x you can use `setPosition(_ minYPosition: CGFloat, animated: Bool)` to change the sheet position programmatically.

**Comment by SwapnanilDhol** [comment]
> after version 1.x you can use `setPosition(_ minYPosition: CGFloat, animated: Bool)` to change the sheet position programmatically.

Hey, can you help me out with the implementation of this. I am trying to move the sheet to a normal height after receiving a delegate call back and if I try to set the minYPosition to any value it stretches the bottom sheet and it takes up the whole screen.

**Comment by OfTheWolf** [comment]
@SwapnanilDhol what did you set for `minYPosition` value? Closer to zero means at top and closer to view.frame.height means at bottom. Stretch happens if it goes over the minimum sheet position (top limit). If you dont want stretch you may want to use scrollView inside the sheet.

**Comment by SwapnanilDhol** [comment]
Hey, thanks a lot. I was referring to the values you mentioned in the previous comment and so I kept using 0.1 to minimise the sheet. I’ve now used an offset of the view’s height and it works perfectly. Thank you for the great library and the quick response!
