### ISSUE TITLE
Trigger on click in UISearch and dismiss in cancel

### ISSUE THREAD

**Issue by isaiasmac** [OfTheWolf/UBottomSheet#17]
I want to show the modal when I click in UISearchBar and hide it when I pressed the cancel button. How can I archive that ?

I'm trying to simulate a PanGesture but nothings happens.

**Comment by OfTheWolf** [comment]
@isaiasmac I guess you wanna show the sheet at top on search click and show at bottom on dismiss. If this is what you want you should use:
```
changePosition(to: .top)  //on search click
changePosition(to: .bottom) //on dismiss
```
