### ISSUE TITLE
Check if a ViewController is attached

### ISSUE THREAD

**Issue by codobuxsocial** [OfTheWolf/UBottomSheet#18]
Is there anyway to check if a viewcontroller is attached because if i by mistake pop a view controller while a bottom sheet controller is attached, the app crashes. Any way to prevent it?

Thanks for this awesome library it is really easy to use!

**Comment by OfTheWolf** [comment]
I can't reproduce. Can you provide some code please?

**Comment by codobuxsocial** [comment]
Nevermind @OfTheWolf managed by taking a global object of attached view controller and detaching it before popping the controller which it was attached to. Another question how can i give dynamic height to view depending on content inside it? For example 2 labels have addresses in them and sometimes they can be of 1 line and sometimes it can be 10 lines. So i have to swipe to see whole content. Any fix for this?

**Comment by OfTheWolf** [comment]
Sorry for late response. I rewrite the project for more flexibility and it took some time. I guess you need autosizing the sheet w.r.t. the content size. There is no support this but if you are able to calculate the size before creating it you can adjust sheet positions according to the content size.
