### ISSUE TITLE
Unable to use pod, missing classes after 'pod install'

### ISSUE THREAD

**Issue by OlafAndreas** [OfTheWolf/UBottomSheet#19]
Only `Extensions.swift` is available after installing the latest version of this pod.

This is because all the other necessary files are not present in the `UIBottomSheet/Classes` folder.

Looks like the changes in 9500e36bba74f9567a779f2fc6d66a281e36b16c caused this.

**Comment by OfTheWolf** [comment]
@OlafAndreas I moved the files to Classes folder and did some other fixes. Please check version "1.0.4".
