### ISSUE TITLE
Fixed minor bug

### ISSUE THREAD

**Issue by super-brian** [OfTheWolf/UBottomSheet#2]
There is a comment in this answer by Jakub Truhlář at Sep 25 at 13:13.
https://stackoverflow.com/a/51768193/8963597

I applied this comment to this code, and what I did was, adding this to BottomSheetViewController
`	var initialContentOffset: CGFloat = 0
	
	func scrollViewWillBeginDragging(_ scrollView: UIScrollView) {
		initialContentOffset = tableView.contentOffset.y
	}`

and modify one line in  handlePan():

`let maxY = max(topY, lastY + dy - initialContentOffset)`

now, when user drags down while table view shows, like from cell 3, after table shows cell 1 fully, the bottom sheet goes down without any jump.

**Comment by rhunt222** [comment]
worked for me, thanks!

**Comment by OfTheWolf** [comment]
jumping problem is fixed with last [commit](https://github.com/OfTheWolf/UBottomSheet/commit/4ac62c399ace52c5ba40877c178c8cb458fc374c).
