### ISSUE TITLE
[Question] Way to scroll tableView in middle position?

### ISSUE THREAD

**Issue by JoseSanchezMirandaRos** [OfTheWolf/UBottomSheet#20]
Hi!

Good job on this! I love it! I added and extra position to the default one, so now I have 3. I have a tableview in the sheet and I'd like to it to be able to scroll the table view cells while in the middle position. It works when on top but in the middle it only detects my swiping so it goes down or up. 

Is there a way to add this? I imported your code so I can make modifications.

Thanks!

**Comment by OfTheWolf** [comment]
Hi @JoseSanchezMirandaRos,
If you don't want to move the sheet with scrollView, so you should set draggableView() to nil or do not implement it as it is set to nil by default. 

```
extension MapsDemoBottomSheetController: Draggable{
    
    func draggableView() -> UIScrollView? {
        return nil // tableView. if set nil tableview will not drive the sheet.
    }
} 
```

**Comment by JoseSanchezMirandaRos** [comment]
@OfTheWolf Thank you so much! I don't know how I missed that! totally worked. Thanks for your contributions!

A little addition: in removeSheet..() you should also add this as it stays right now.

self?.dropShadowView?.removeFromSuperview()

Thanks!

**Comment by OfTheWolf** [comment]
You are right. Actually i first intended to put adding shadow outside of the library. But with blur background adding shadow is really challenging. So i put it inside code and forget to remove. but it still needs to be improved. Thanks for the feedback.
