### ISSUE TITLE
[Question] Possibility of extending over the navigation bar

### ISSUE THREAD

**Issue by alex-de-waal** [OfTheWolf/UBottomSheet#22]
Is there a possibility of having the sheet extend over a navigation bar and not just underneath it?

**Comment by OfTheWolf** [comment]
I didn't understand the question.can you plot it? Or tell me the layout structure that is in your mind please. @alex-de-waal

**Comment by alex-de-waal** [comment]
So the sheet has different positions of where it can stop, either at the bottom, middle or at the very top just underneath the navigation bar. I’d like to know if it can go over the navigation bar as shown in the image attached. This is an example from the GitHub iOS app. 

![image](https://user-images.githubusercontent.com/60880336/81221314-f3917b00-8fe2-11ea-85df-48d072b1b8bb.png)

**Comment by OfTheWolf** [comment]
@alex-de-waal
Sheet is just a container view inside any viewcontroller. So you can use a viewcontroller with clear background for sheet controller. and as it is transparent your back vc can have a navbar and it will go over it as you need.

```
        let vc = TransparentViewController() /// create your sheet inside it just like in MapsViewController
        vc.view.backgroundColor = .clear
        vc.modalPresentationStyle = .overFullScreen
        self.present(vc, animated: true, completion: nil) /// 'self' is your vc with navbar 
```
P.S. Don't forget to set TransparentViewController.view as PassThroughView to allow taps behind.

**Comment by alex-de-waal** [comment]
Awesome, I’ll try that. Thank you do much.

**Comment by alex-de-waal** [comment]
@OfTheWolf It works, which is great. It's just the PassThroughWindow that didn't work. No touches are passing through the view.

**Comment by OfTheWolf** [comment]
@alex-de-waal You are right. It is view controller not just view so PassThroughView is not enough. I found a solution how to pass touches through view controllers in this SO [link](https://stackoverflow.com/a/53922625/5923606). 

1. So first create a TouchDelegatingView class.

```
class TouchDelegatingView: UIView {
    weak var touchDelegate: UIView? = nil


    override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        guard let view = super.hitTest(point, with: event) else {
            return nil
        }

        guard view === self, let point = touchDelegate?.convert(point, from: self) else {
            return view
        }

        return touchDelegate?.hitTest(point, with: event)
    }
}
```

2. Then set your TransparentViewController view class to TouchDelegatingView.

3. And bind this touchDelegate to back view controller(presentingViewController)'s view in viewDidAppear.

 ```
   override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        if let delegatingView = view as? TouchDelegatingView {
            delegatingView.touchDelegate = presentingViewController?.view
        }
    }
```

It worked for me. You can try this.

**Comment by alex-de-waal** [comment]
Great! Thank you, I appreciate the help @OfTheWolf
