### ISSUE TITLE
Can't override UBottomSheetCoordinatorDataSource functions

### ISSUE THREAD

**Issue by aeharding** [OfTheWolf/UBottomSheet#23]
Hello!

Thanks for all your work on this project.

For some reason, I'm having difficulties overriding `sheetPositions` and `initialPosition`.

When I add this to my UIViewController:

```
    func initialPosition(_ availableHeight: CGFloat) -> CGFloat {
        return 1
    }
```

nothing happens. Default functionality continues. And when I debug what the coordinator is calling, the default function's value is returned.

I have verified I am calling `UBottomSheetCoordinator(parent: self)` and adding the `initialPosition` function to `self`.

I've also tried what the examples say (haven't actually tried running them) like this:

```
import UBottomSheet

class MyDataSource: UBottomSheetCoordinatorDataSource {
    func initialPosition(_ availableHeight: CGFloat) -> CGFloat {
        return 1
    }
}
```

but that doesn't work, `UBottomSheetCoordinator.dataSource` is private so I can't set it directly like in `SimpleViewController.swift`,

Any help is appreciated!

**Comment by OfTheWolf** [comment]
@aeharding

First, use height value as position not percent for `initialPosition` and `sheetPositions`. 
```
func initialPosition(_ availableHeight: CGFloat) -> CGFloat {
        return 1*availableHeight
    }
```

Second, datasource made public in last version. 1.0.5 i guess. So now you can use it to set custom data source or implement data source where you create UBottomSheetCoordinator(parent: self). self refers to datasource too if there is.

See the [link](https://github.com/OfTheWolf/UBottomSheet/blob/master/Example/UBottomSheet/ViewControllers/SimpleViewController/SimpleViewController.swift#L31) for custom data source usage.

**Comment by aeharding** [comment]
Hi @OfTheWolf 
Thanks, I figured the problem out. I was using 1.0.4 temporarily to debug, and forgot to switch back. dataSource is public in 1.0.5.

Thanks again for your help, and have a great day.
