### ISSUE TITLE
Example Project build error

### ISSUE THREAD

**Issue by aalaaeid** [OfTheWolf/UBottomSheet#24]
I tried to build and run the example project on xcode 11 ,but it shows a weird bug 
![Screen Shot 2020-05-13 at 2 05 20 AM](https://user-images.githubusercontent.com/37640295/81757300-b8012000-94be-11ea-9876-f73390030a6c.png)

**Comment by OfTheWolf** [comment]
@aalaaeid are you running on a real device? It seems code signing issue. Just check your developer certificate or maybe a keychain issue. You might try first on ios simulator.

**Comment by aalaaeid** [comment]
no, i'm running it on ios simulator and i've checked this solution for the keychain issue, it didn't work either
https://stackoverflow.com/questions/52421999/xcode-10-command-codesign-failed-with-a-nonzero-exit-code

**Comment by OfTheWolf** [comment]
You can create a new project and see if it runs on an ios simulator. Because this issue is not related to this project. There must be sth wrong in your environment.
