### ISSUE TITLE
DropShadowView (PassThroughView) is not removed when we call the removeSheet()

### ISSUE THREAD

**Issue by MyoThuraZaw** [OfTheWolf/UBottomSheet#25]
When the `removeSheet()` is called, it only removes the bottom sheet. The `dropShadowView` behind remains on the screen. Besides, `dropShadowView` property is private which makes it hard to remove it manually.  It would be convenient to add a public function to remove the `dropShadowView` or automatically remove it from inside the `removeSheet()`

**Comment by OfTheWolf** [comment]
@MyoThuraZaw It is fixed in 1.0.6. You can update your pod now.

**Comment by MyoThuraZaw** [comment]
Thank you for your fast response.
