### ISSUE TITLE
topY position

### ISSUE THREAD

**Issue by rhunt222** [OfTheWolf/UBottomSheet#3]
I'm trying to set my topY to be a little bit higher on the screen. 

When setting it to:
`UIScreen.main.bounds.height * 0.10`
It moves up great and the table scrolls, however when I change to: 
`UIScreen.main.bounds.height * 0.05`
The bottom sheet moves up to my ideal position but the tableview will no longer scroll. I'm assuming I have to adjust something in the handlePan func?

**Comment by OfTheWolf** [comment]
`topY = UIScreen.main.bounds.height * 0.05` is `33.350000000000001` on iphone 8 and `parentView.minY = 33.350000000000002` somehow. in fact they must be the same in top position. So the logic assumes never reached the top so sets tableview contentOffset to zero which stops scrolling. So rounding the initial value solves the problem.
```
//Better to set this in viewWillAppear
self.topY = round(UIScreen.main.bounds.height * 0.05)
```

**Comment by rhunt222** [comment]
Thanks! Was just printing out these numbers and noticed the same. Rounding definitely works.
