### ISSUE TITLE
Make the sheet modal?

### ISSUE THREAD

**Issue by garyhooper** [OfTheWolf/UBottomSheet#34]
Instead of passing taps through to the underlying view controller, what is the most straight forward way to intercept them in order to dismiss the sheet, thereby treating the sheet as modal?

**Comment by OfTheWolf** [comment]
@garyhooper

First change access level of `private var draggables: [DraggableItem]` property to public in `UBottomSheetCoordinator.swift `and then you can add below code to your parent view where u create `UBottomSheetCoordinator`.
    
```
//UBottomSheetCoordinator.swift
public var draggables: [DraggableItem] = []
```

```
//MapsViewController.swift
 override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        super.touchesBegan(touches, with: event)
        let touch = touches.first
        guard let location = touch?.location(in: view) else { return }
        if sheetCoordinator!.draggables.first(where: { (item) -> Bool in
            item.view.convert(item.view.frame, to: self.view).contains(location)
        }) == nil{
            print("Tapped outside the view")
        } else {
            print("Tapped inside the view")
        }
    }
```

**Comment by garyhooper** [comment]
Yes, this works well.  Thanks!  (It would be great if a future update could make `draggables` public.)
