### ISSUE TITLE
Stop dragging below the initial position and beyond the max top position

### ISSUE THREAD

**Issue by prashantAlgante** [OfTheWolf/UBottomSheet#36]
Hello,

How to STOP dragging the sheet below the Initial point. And the same way Beyond the Max top position. Can you give this feature in next update. Or if you can give a quick fix As i need to do this.

Thanks in Advance.

**Comment by OfTheWolf** [comment]
@prashantAlgante 
implement UBottomSheetCoordinatorDataSource in your viewcontroller. See below datasource methods. I didn't try but it must work. 

 ```
//disable top rubberbanding
public func rubberBandLogicTop(_ total: CGFloat, _ limit: CGFloat) -> CGFloat{
     return limit
}
 
//disable bottom rubberbanding
public func rubberBandLogicBottom(_ total: CGFloat, _ limit: CGFloat) -> CGFloat {
     return limit
 }
```

**Comment by prashantAlgante** [comment]
Yes , it is working
