### ISSUE TITLE
How can check in bottom sheet have sheet or not?

### ISSUE THREAD

**Issue by minhson95th** [OfTheWolf/UBottomSheet#38]
1. I want to check if in bottom sheet have sheet, i'll remove it and add new sheet. How can i do? When i click button, first time app will crash:

```
//app will crash when run first time
_sheetCoordinator.removeSheet()
let MeasurementVC = UIStoryboard(name: "Measurement", bundle: nil).instantiateViewController(withIdentifier: "MeasurementViewController") as! MeasurementViewController
MeasurementVC.sheetCoordinator = self._sheetCoordinator
MeasurementVC.dataSource = MyDataSource()
MeasurementVC.mapView = self.mapView
_sheetCoordinator.addSheet(MeasurementVC, to: self, didContainerCreate: { container in
    let f = self.view.frame
    let rect = CGRect(x: f.minX, y: f.minY, width: f.width, height: f.height)
    container.roundCorners(corners: [.topLeft, .topRight], radius: 10, rect: rect)
})
```
2. how can remove sheet when dismiss bottomsheet?

**Comment by OfTheWolf** [comment]
@minhson95th  It crashes because of force-unwrapping of containerView in removeSheet method. 

1. Either use below 
```
sheetCoordinator.removeSheet { container in
            UIView.animate(withDuration: 0.3, animations: {[weak self] in
                guard let sSelf = self, let container = container else {return}
                container.frame = container.frame.offsetBy(dx: 0, dy:  sSelf.parent.view.frame.height)
            }) {[weak self]  (finished) in
                container?.removeFromSuperview()
            }
}
```

2. or fix force unwrapping in the library. See [UBottomSheetCoordinator.swift#L294](https://github.com/OfTheWolf/UBottomSheet/blob/master/Sources/UBottomSheet/Classes/UBottomSheetCoordinator.swift#L294)
```
 public func removeSheet(_ block: ((_ container: UIView?)->Void)? = nil){
...
 guard let sSelf = self, let container = container else {return}
 container.frame = container.frame.offsetBy(dx: 0, dy:  sSelf.parent.view.frame.height)
```

**Comment by minhson95th** [comment]
> @minhson95th It crashes because of force-unwrapping of containerView in removeSheet method.
> 
> 1. Either use below
> 
> ```
> sheetCoordinator.removeSheet { container in
>             UIView.animate(withDuration: 0.3, animations: {[weak self] in
>                 guard let sSelf = self, let container = container else {return}
>                 container.frame = container.frame.offsetBy(dx: 0, dy:  sSelf.parent.view.frame.height)
>             }) {[weak self]  (finished) in
>                 container?.removeFromSuperview()
>             }
> }
> ```
> 
> 1. or fix force unwrapping in the library. See [UBottomSheetCoordinator.swift#L294](https://github.com/OfTheWolf/UBottomSheet/blob/master/Sources/UBottomSheet/Classes/UBottomSheetCoordinator.swift#L294)
> 
> ```
>  public func removeSheet(_ block: ((_ container: UIView?)->Void)? = nil){
> ...
>  guard let sSelf = self, let container = container else {return}
>  container.frame = container.frame.offsetBy(dx: 0, dy:  sSelf.parent.view.frame.height)
> ```

this is alert when unwrapping in the library
`Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/super/Desktop/danang/DaNangNguoiDan/Pods/UBottomSheet/UBottomSheet/Classes/UBottomSheetCoordinator.swift, line 294`
this is line 294 
` container.frame = container.frame.offsetBy(dx: 0, dy:  sSelf.parent.view.frame.height)`

**Comment by OfTheWolf** [comment]
I know I offered the solution. Just try it.

**Comment by minhson95th** [comment]
> I know I offered the solution. Just try it.

oh, it's work. Thanks for your solution!

**Comment by minhson95th** [comment]
One more question: How can i change height of sheet?
i've create data source for sheet
```
class SearchDataSource: UBottomSheetCoordinatorDataSource {
    func sheetPositions(_ availableHeight: CGFloat) -> [CGFloat] {
        return [0.01, 0.6, 0.91].map{$0*availableHeight}
    }
    
    func initialPosition(_ availableHeight: CGFloat) -> CGFloat {
        return availableHeight*0.01
    }
}
```
i want when i click button, sheet from fullscreen change to half screen. How can i do? I've try with 
`    sheetCoordinator?.setPosition(0.36, animated: false)
`
but it not work

**Comment by OfTheWolf** [comment]
setPosition's first parameter is not percent. it must be the CGFloat value from top. Or use percent * maxAvailableHeight.

`sheetCoordinator?.setPosition(0.36 * maxAvailableHeight, animated: false)
`
