### ISSUE TITLE
How to use the code way?

### ISSUE THREAD

**Issue by gaohomway** [OfTheWolf/UBottomSheet#4]
**Thank you very much for contributing this library.**
```swift
func initContainer() {
        container = UIView()
        container.backgroundColor = UIColor.white
        container.frame = CGRect(x: 0, y: 300, width: boundW, height: boundH/2)
        container.layer.cornerRadius = 15
        container.layer.masksToBounds = true
        view.addSubview(container)
        
        bottomSheetController = BottomSheetController()
        bottomSheetController.bottomSheetDelegate = self
        bottomSheetController.parentView = container
        addChildViewController(bottomSheetController)
        container.addSubview(bottomSheetController.view)
        bottomSheetController.didMove(toParentViewController: self)
        
    }

```
**In this way, I seem to have problems, the table can't scroll**

**Comment by OfTheWolf** [comment]
tableview and panview are created from storyboard and has references via outlets. if you choose creating your viewcontroller programmatically you should also create other layout elements(table, panView, searchbar etc. ) in the BottomSheetController.

**Comment by gaohomway** [comment]
I solved this problem with code.

Swipe down quickly to the original position. Is this specially designed? Can I cancel?

**Comment by OfTheWolf** [comment]
you can change it in handlePan method.  when the pan gesture  .failed, .ended or .cancelled, it is animating to the closest level (top, middle or bottom). you can remove or update these stuff as you wish.

**Comment by OfTheWolf** [comment]
This is more like stackoverflow question than an issue so i am closing it.

**Comment by gaohomway** [comment]
I solved the problem of free sliding and needed to add a free state.

**status**
```swift
enum SheetLevel {
    case top, bottom, middle, freedom
}
```
**handlePan**
```swift
if lastLevel == .top || lastLevel == .freedom {
    disableTableScroll = false
}else{
    disableTableScroll = true
}
```

**nextLevel**
```swift
if velY < -200 {
    return y > middleY ? .middle : .top
}else if velY > 200 {
    if tableView.contentOffset.y > 0 {
        return .freedom
    }else{
        return y < (middleY + 1) ? .middle : .bottom
    }
}else{
    if y > middleY {
        return (y - middleY) < (bottomY - y) ? .middle : .bottom
    }else{
        return (y - topY) < (middleY - y) ? .top : .middle
    }
}
```

It works very well temporarily, thank you very much for your library.
