### ISSUE TITLE
SPM install error

### ISSUE THREAD

**Issue by mmbabaev** [OfTheWolf/UBottomSheet#43]
Hello,  I can't install library with SPM. Error is on the screenshot.

<img width="726" alt="Снимок экрана 2020-10-14 в 10 02 07" src="https://user-images.githubusercontent.com/12600807/95954727-69a4d400-0e04-11eb-933c-1227edd96f5e.png">

**Comment by OfTheWolf** [comment]
@mmbabaev fixed in 1.0.8.
