### ISSUE TITLE
How to catch when sheet is dismissed? in delegate or other method 

### ISSUE THREAD

**Issue by cancem123** [OfTheWolf/UBottomSheet#44]
First of all thank you for your source.

I'm trying to find out how to know when the sheet is dismissed? I have tried to find it in`UBottomSheetCoordinatorDelegate but there is only there three function. I'm using `Pull To Dismiss` as in the demo. Could you help me with it?

**Comment by OfTheWolf** [comment]
You are welcome @cancem123. 

Below example shows how to use delegate methods to detect dismissal of the sheet. The point is when it dismissed percent will be lower than zero. So `percent < 0` in `finished` (called after animation completed) and `willFinish`(before animation) means sheet is dismissed.

```
extension SimpleViewController: UBottomSheetCoordinatorDelegate{
    func bottomSheet(_ container: UIView?, didChange state: SheetTranslationState) {
        switch state {
        case .progressing(_, let percent): 
            break
        case .willFinish(_, let percent):
            print("log is dismissed: ", percent < 0)
        case .finished(_, let percent):
            print("log is dismissed and animation completed: ", percent < 0)
        }
    }
}
```

**Comment by cancem123** [comment]
Thank you it works 👍

**Comment by SohaibSiddique** [comment]
> You are welcome @cancem123.
> 
> Below example shows how to use delegate methods to detect dismissal of the sheet. The point is when it dismissed percent will be lower than zero. So `percent < 0` in `finished` (called after animation completed) and `willFinish`(before animation) means sheet is dismissed.
> 
> ```
> extension SimpleViewController: UBottomSheetCoordinatorDelegate{
>     func bottomSheet(_ container: UIView?, didChange state: SheetTranslationState) {
>         switch state {
>         case .progressing(_, let percent): 
>             break
>         case .willFinish(_, let percent):
>             print("log is dismissed: ", percent < 0)
>         case .finished(_, let percent):
>             print("log is dismissed and animation completed: ", percent < 0)
>         }
>     }
> }
> ```

Copy and paste this code in SimpleViewController of Example, but it did not work for me, any solution please?
