### ISSUE TITLE
Customise drop shadow radius and height.

### ISSUE THREAD

**Issue by prashantAlgante** [OfTheWolf/UBottomSheet#45]
Hello @OfTheWolf  can you please tell how to customise the drop shadow radius. 

I tried using  as below but of no use

```
sheetCoordinator.addSheet(vc, to: self, didContainerCreate: { container in
            container.newShadow() //<<<============= here
            let f = self.view.frame
            let rect = CGRect(x: f.minX, y: f.minY, width: f.width, height: f.height)
            container.roundCorners(corners: [.topLeft, .topRight], radius: 25, rect: rect)
        })
```

Can you please help.

**Comment by OfTheWolf** [comment]
@prashantAlgante What is inside your newShadow() extension? See `addDropShadowIfNotExist()` in `UBottomSheetCoordinator.swift` and `MapsViewController.swift` to see how drop shadow is used. i.e. `sheetCoordinator.setCornerRadius(10)` updates corner radius of drop shadow which added via `addDropShadowIfNotExist()`.

**Comment by prashantAlgante** [comment]
@OfTheWolf  see below code 

 `private func applyDefaultShadowParams(){`
          dropShadowView?.layer.shadowPath = UIBezierPath(roundedRect: getInitialFrame(), cornerRadius: cornerRadius).cgPath
        dropShadowView?.layer.shadowColor = UIColor.black.cgColor
       ` dropShadowView?.layer.shadowRadius = CGFloat.init(10)` //<<===== **This "10" value is hardcoded by you.  I want to lower this value**
//        dropShadowView?.layer.shadowOpacity = Float.init(0.5)
.........
}

to achieve this effect for ` dropShadowView?.layer.shadowRadius = CGFloat.init(4)` 
![Screenshot 2020-10-21 at 11 21 51 AM](https://user-images.githubusercontent.com/66359785/96678630-b7cf4f80-138f-11eb-9f0d-cbb07a8c1ae6.png)


 sheetCoordinator.setCornerRadius(10) <<== **you are using this in setting corner radius of shadowPath only.**

**Comment by OfTheWolf** [comment]
@prashantAlgante Aha ok. I am confused with cornerRadius. So here is `addDropShadowIfNotExist`. And if you are using translucent background just like apple maps. don't forget to write your own method to clip inner shadow background. something like clearShadowBackground().

```
extension MapsViewController: UBottomSheetCoordinatorDelegate{
    
    func bottomSheet(_ container: UIView?, didPresent state: SheetTranslationState) {
        self.sheetCoordinator.addDropShadowIfNotExist { (shadowView) in
            //TODO tweak shadow parameters
        }
        self.handleState(state)
    }
```

**Comment by prashantAlgante** [comment]
@OfTheWolf 

```
 func bottomSheet(_: UIView?, didPresent state: SheetTranslationState) {
       sheetCoordinator?.addDropShadowIfNotExist { shadowView in
            // TODO: tweak shadow parameters
            shadowView.layer.shadowColor = UIColor.black.cgColor
            shadowView.layer.shadowRadius = CGFloat(4)
            shadowView.layer.shadowOffset = CGSize(width: 0.0, height: 4.0)
        }
        handleState(state)
    }
```

after this the default shadow is getting removed. But no new shadow is visible.

**Comment by OfTheWolf** [comment]
@prashantAlgante shadowOpacity and shadowPath is the key.
```
 self.sheetCoordinator.addDropShadowIfNotExist { (view) in
            view.layer.shadowPath = UIBezierPath(roundedRect: container!.frame,
                                                 cornerRadius: 10).cgPath
            view.layer.shadowRadius = 100
            view.layer.shadowOpacity = 0.5
            view.layer.shadowOffset = CGSize.init(width: 0.0, height: 4.0)
            view.layer.shadowColor = UIColor.black.cgColor
        }
```
