### ISSUE TITLE
TableView inside Sheet controller won't register first touch.

### ISSUE THREAD

**Issue by JoseSMRos** [OfTheWolf/UBottomSheet#47]
So I have a tableView inside the sheet controller and the didSelectRowAtIndexpath doesn't trigger on first touch right after I end up dragging the sheet. After dragging the sheet then all touches are working as expected in the cells, however if you scroll the sheet again it will make the bug happen again. Any idea of what could be happening?

**Comment by JoseSMRos** [comment]
Found the solution; for anyone having this problem, in ` public func startTracking<T: DraggableItem>(item: T){` add `pan.cancelsTouchesInView = false`. This lets the tableView be active on first touch.

**Comment by OfTheWolf** [comment]
@JoseSMRos This is not happening in the examples. And it seems you've already found a solution to your problem. So i close the issue. Feel free to open if still exists.
