### ISSUE TITLE
Auto size UINavigationController

### ISSUE THREAD

**Issue by CripyIce** [OfTheWolf/UBottomSheet#48]
Hi there,
How can I implement UINavigationController inside bottom sheet with auto height?
I have a UINavigationController with multiple UIVIewControllers and all views inside are constrained to the "superview" and I've tried using `translatesAutoresizingMaskIntoConstraints = false` with no success.

Any ideas?
Thanks!

**Comment by OfTheWolf** [comment]
Hi @CripyIce,

How does it look like? Can you share screenshot please?

And bottom sheet does not support auto height. But you can calculate the height of your inner viewController/navController and change the position of the sheet accordingly.

**Comment by OfTheWolf** [comment]
Duplicate of #51
