### ISSUE TITLE
tableView( didSelectRowAt ) is not called after...

### ISSUE THREAD

**Issue by super-brian** [OfTheWolf/UBottomSheet#5]
Before applying commit "topY related bug fix (issue #3)" or after, this problem persists:

after I close the bottom sheet vc, if I make it show to the top, then tapping the first time on one of the table view cells doesn't call tableView( didSelectRowAt ) on  (though cell's background becomes darker then normal during tapping). Tapping the second or later time, or after I scroll the tableView of bottom sheet vc, it works very good.

For better understanding, I made a short captured video and uploaded into dropbox:
https://www.dropbox.com/s/322x7bk30ndh2d8/ScreenRecording_11-17-2018%2019-26-20.MP4?dl=0

I moved down the bottom sheet vc by hand first. then when it is showed up, tapping on one of the cells doesn't work (though you can see the cell's background becomes darker for a second), but then the second time, it works.

Now I applied your commit.

**Comment by OfTheWolf** [comment]
This is strange. Probably using both the tableView and panView gesture recognizers simultaneously confuses tableView. I will investigate it.

**Comment by super-brian** [comment]
Note that this may be because... I used another view for gesture. (now I deleted it)
Now, for search/list, I don't use bottom sheet anymore, though for recent I still use it.
But it may be worth checking.

**Comment by OfTheWolf** [comment]
@moreinf thanks for pointing out this issue. Listening pan gestures in superview causes the bug. As I cant change the pan gestures i decided to use tap gesture simultaneously for tableview and detect the tapped row from the touched point. Just beware of the didselect method will not triggered if you are already using it as i call tableView selectRow method. You should handle selected row in handleTap function now.
