### ISSUE TITLE
Bottom sheet cannot be dragged gradually when UIScrollView contents are able to fit the screen and bounce is off

### ISSUE THREAD

**Issue by iori57** [OfTheWolf/UBottomSheet#50]
Thanks for the awesome library!

There's a small issue where the bottom sheet cannot be dragged gradually but will jump instantly to the next position if all contents in a scroll view are able to fit and scrollView.alwaysBounceVertical = false (which is the default in current iOS version)
No issue when content is long enough that it can be scrolled even when bounce is disabled.

The workaround is to set alwaysBounceVertical = true, however this will have a minor side effect of having the content to bounce when user tries to scroll the content up, even though content fits the screen.

Cheers
Bruce

**Comment by iori57** [comment]
Thanks for fixing it so quickly! I am new to iOS development and usage of Pods, do I have to wait until the next release in order to get the fix? Is there a way to pull the specific git commit to be used in the iOS project?

**Comment by OfTheWolf** [comment]
@iori57 i released the new changes. so you can update your pod to 1.0.9.
