### ISSUE TITLE
Convert initialPosition to initialHeight

### ISSUE THREAD

**Issue by EmreSURK** [OfTheWolf/UBottomSheet#52]
Hi, thanks for the great library.
I think you should change initialPosition to initialHeight. Developers should not worry about the position, they almost always working on height property. 

Thanks.

**Comment by OfTheWolf** [comment]
Hi @EmreSURK, Actually it is not height but minY position. And height is  `availableHeight - position`

See how it is used in [UBottomSheetCoordinator.swift#L592](https://github.com/OfTheWolf/UBottomSheet/blob/master/Sources/UBottomSheet/Classes/UBottomSheetCoordinator.swift#L592) 

```
let height = max(availableHeight - minSheetPosition!, availableHeight - position)
let frame = CGRect(x: 0, y: position, width: oldFrame.width, height: height)
```

Sheet positions are meant to be defined as percent of availableHeight. You can not locate a view with height property. You may want to stretch (height changing) or move (height fixed) sheet by pan gesture and handling two these two cases with height does not make sense.
