### ISSUE TITLE
Not able to build and run UBottomSheet-Example using XCode 12.3 (12C33)

### ISSUE THREAD

**Issue by yccheok** [OfTheWolf/UBottomSheet#53]
Hi,

Thank you for creating useful bottom sheet library.

I am using Xcode 12.3 (12C33), macOS Catalina 10.15.7

I tried to build and run UBottomSheet-Example, after checkout without any modification, from git@github.com:OfTheWolf/UBottomSheet.git

I am getting the following error

> /Users/yccheok/Desktop/github/UBottomSheet/Example/Pods/Target Support Files/Pods-UBottomSheet_Example/Pods-UBottomSheet_Example.debug.xcconfig: unable to open file (in target "UBottomSheet_Example" in project "UBottomSheet")

![Screenshot 2021-01-02 at 9 55 15 PM](https://user-images.githubusercontent.com/308276/103458732-ebdacf80-4d45-11eb-9736-d28af9537705.png)

Note that, under `Pods` and `Frameworks`, I am getting red color error.

![Screenshot 2021-01-02 at 10 02 25 PM](https://user-images.githubusercontent.com/308276/103458775-42480e00-4d46-11eb-982b-ad160bbb1055.png)

Any idea on how to resolve this is very much appreciated. Thank you.

**Comment by OfTheWolf** [comment]
@yccheok you should run UBottomSheet.xcworkspace in Example folder.

**Comment by yccheok** [comment]
@OfTheWolf

Thanks for responding. I must be doing something wrong in between. But, I am not sure what's wrong.

I first post outcome, is due to I am opening xcodeproj file

![xcodeproj](https://user-images.githubusercontent.com/308276/103471678-16686f00-4dbe-11eb-9791-5e80be354da6.png)

So, right now, I tried to open xcworkspace file

![xcworkspace](https://user-images.githubusercontent.com/308276/103472056-a78e1480-4dc3-11eb-8200-d5104c910ef8.png)

I'm still getting the similar error messages

![0](https://user-images.githubusercontent.com/308276/103472069-b83e8a80-4dc3-11eb-8745-2fab26a1c42c.png)


> /Users/yccheok/Desktop/github/UBottomSheet/Example/Pods/Target Support Files/Pods-UBottomSheet_Example/Pods-UBottomSheet_Example.release.xcconfig: unable to open file (in target "UBottomSheet_Example" in project "UBottomSheet")

But, this time, it comes with additional error message

![1](https://user-images.githubusercontent.com/308276/103472083-e0c68480-4dc3-11eb-889a-1a7681174835.png)

> No account for team "MNQ5D2G6V5". (Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.)

So far, I haven't paid to Apple to register as their developer officially, and I also never publish any app yet to Apple AppStore.

However, I still try to input my Apple ID account in Xcode

![2](https://user-images.githubusercontent.com/308276/103472096-27b47a00-4dc4-11eb-868c-c252ed17e95a.png)


![3](https://user-images.githubusercontent.com/308276/103472099-2d11c480-4dc4-11eb-8709-06da5dc1058c.png)

I read through https://stackoverflow.com/questions/48584288/code-signing-no-account-for-team-message-when-signing-for-different-developer/50424214 , but have no idea how to follow the suggestions from 1st & 2nd answers

Not sure start to pay to Apple to resolve this issue, although I really do not wish to pay yet, till I am ready to publish the app.

Do you have any suggestion on this issue? Thank you.

**Comment by OfTheWolf** [comment]
This is not related to this library. Please don't post personal issues here. Use stackoverflow instead.

You can run in simulator by selecting None for Team as shown below.
 
![image](https://user-images.githubusercontent.com/42251802/103476808-d60eee00-4dc9-11eb-9a78-5fcd65590a8b.png)
