### ISSUE TITLE
how to set the top hight of the bottomSheet?

### ISSUE THREAD

**Issue by muhammadahmad665** [OfTheWolf/UBottomSheet#54]
I want to set it close to the superView but it covers only on 80% of the screen. Help me here, please?

**Comment by OfTheWolf** [comment]
@MuhammadAhmad665

By default sheet min max positions were set to 0.2 to 0.7 of the superview height. So you should use custom data source instead. See [custom data source](https://github.com/OfTheWolf/UBottomSheet/blob/master/Example/UBottomSheet/DataSource/MyDataSource.swift ) example. 

See [UBottomSheetCoordinatorDataSource.swift#L38](https://github.com/OfTheWolf/UBottomSheet/blob/master/Sources/UBottomSheet/Classes/UBottomSheetCoordinatorDataSource.swift#L38) 
```
///Default data source implementation
extension UBottomSheetCoordinatorDataSource {
    public func sheetPositions(_ availableHeight: CGFloat) -> [CGFloat] {
        return [0.2, 0.7].map { $0 * availableHeight }
    } 
```
