### ISSUE TITLE
Issue in view

### ISSUE THREAD

**Issue by haswiniparmar1** [OfTheWolf/UBottomSheet#56]
I want to open the bottom sheet only half, when it is presented.How can  I do it?

**Comment by OfTheWolf** [comment]
@haswiniparmar1 
Check custom data source example and implement `func initialPosition(..)`.

See Example/...[/MyDataSource.swift](https://github.com/OfTheWolf/UBottomSheet/blob/master/Example/UBottomSheet/DataSource/MyDataSource.swift
)
```
class MyDataSource: UBottomSheetCoordinatorDataSource {
    func sheetPositions(_ availableHeight: CGFloat) -> [CGFloat] {
        return [0.2, 0.4, 0.6, 0.8].map{$0*availableHeight}
    }
    
    func initialPosition(_ availableHeight: CGFloat) -> CGFloat {
        return availableHeight*0.4 /// %100 means full height open. 
    }
}
```
