### ISSUE TITLE
Odd blank area added in AppleMaps example

### ISSUE THREAD

**Issue by gammelby** [OfTheWolf/UBottomSheet#57]
If I use the `MyDataSource` example with the Apple Maps example, I see a large white area above the top of the maps sheet (very visible in dark mode). It goes away if dragging the sheet up and back again.

The following causes the problem (the default example data source):

```
class MyDataSource: UBottomSheetCoordinatorDataSource {
    func sheetPositions(_ availableHeight: CGFloat) -> [CGFloat] {
        return [0.2, 0.4, 0.6, 0.8].map{$0*availableHeight}
    }

    func initialPosition(_ availableHeight: CGFloat) -> CGFloat {
        return availableHeight*0.4
    }
}
```

After playing a bit with the values, it seems the problem is evident if `initialPosition` returns a value larger than the smallest value returned from `sheetPositions`. So if removing 0.2 from the array or changing 0.4 to 0.2 in `initialPosition`, the problem in the above example is remedied.

However, this is problematic if you want to start out with a small sheet that can be dragged up.

Is this some artifact of the example or an issue with the library?

Thanks for a nice library and in advance for any assistance,

Ulrik

**Comment by OfTheWolf** [comment]
It seems safe area bug. Open AppleMapsSheetViewController.xib and change top constraint to superview instead of safe area.

![image](https://user-images.githubusercontent.com/42251802/108939550-f0937400-7662-11eb-859a-aa40d9843dc4.png)
