### ISSUE TITLE
problem of topY related bug fix (issue #3)

### ISSUE THREAD

**Issue by super-brian** [OfTheWolf/UBottomSheet#6]
Thanks for the update (commit), but it doesn't work well as mine.
try dragging down when the table shows from, like, the third cell.
there is 'jump'...

**Comment by OfTheWolf** [comment]
I can't reproduce the problem. Can you provide more info?

**Comment by super-brian** [comment]
So, first move the table view down so that it shows from 3rd cell, for example.
Then in one drag, try to show the first cell, and keep dragging down, to move the sheet down.
You will see 'jump' with your latest commit.

**Comment by OfTheWolf** [comment]
actually this bug happened before last commit and now i don't see this problem. i will try to reproduce it.

**Comment by OfTheWolf** [comment]
hey @moreinf. see my last commit. i hope it works for you.
