### ISSUE TITLE
Handle provided at the top of bottom sheet is not responsive

### ISSUE THREAD

**Issue by vdfalke** [OfTheWolf/UBottomSheet#7]
If tableview is scrolled (content offset is not equal to zero), user is not able to drag the bottom sheet down. User has to scroll the total tableview down (make content offset as zero) then only user can drag bottom sheet. 
Is there any way we can drag bottom sheet up/down using the handle provided at top irrespective of the scrollview content offset.

let location = pan.location(in: panView)
location.y <= 50

**Comment by vdfalke** [comment]
It will be helpful if you provide an answer for this asap. 
Thanks in advance

**Comment by vdfalke** [comment]
@OfTheWolf can you please look into this

**Comment by OfTheWolf** [comment]
@vipinfalke it was the intended behaviour in my case and to change this i need to rewrite the whole logic. if it is urgent i recommend you to handle pan gesture just for the top view(i.e. searchbar in my demo) and don't handle the pan gesture for tableview. so tableview will be just for scroll and top view for the moving up and down. It is really easy to implement. i hope it works for you. 

And I will try to do your request when i have time.

**Comment by sreejithexp** [comment]
@vipinfalke 

> @OfTheWolf can you please look into this

If you find the solution please let me know. :)

**Comment by vi** [comment]
> @vi

Maybe you meant "@vipinfalke"?

**Comment by cocodyrockstar** [comment]
@vipinfalke yyou can do that by resetting the tableview contentoffset when detecting touch on this view or 
<img width="394" alt="Capture d’écran 2019-03-22 à 07 05 24" src="https://user-images.githubusercontent.com/42719322/54803781-34102700-4c71-11e9-8ea8-a49bd75b71c1.png">

**Comment by OfTheWolf** [comment]
@vipinfalke I updated the repo and now the view is responsive all the time whatever the scroll content offset is . See example project.
