### ISSUE TITLE
What if I want to fix the view but still want to make tableView scrollable?

### ISSUE THREAD

**Issue by super-brian** [OfTheWolf/UBottomSheet#8]
Thank you again for your project. But new issue is that I use bottom up view sometime as bottom up, sometimes as a 'fixed' one using a variable isFixed. But then, just putting the code below inside handlePan() (as well as disable initial resizing) doesn't work.

        if let fixed = isFixed, fixed == true {
            print("\(getTimeMS()) BottomUpVC.handlePan(): isFixed!")
            return
        }

Any solution?

**Comment by super-brian** [comment]
I think I found the solution:

    func scrollViewDidScroll(_ scrollView: UIScrollView) {
		
        guard scrollView == tableView else { return }

        if isFixed == nil || isFixed! == false {
            if (self.delegate!.getBottomUpTopConstraintConstant() > topY) {
                self.tableView.contentOffset.y = 0
            }
        }
    }

**Comment by OfTheWolf** [comment]
also return from scrollViewWillEndDragging when fixed
