### ISSUE TITLE
Use with different view type

### ISSUE THREAD

**Issue by gerrithu** [OfTheWolf/UBottomSheet#9]
More like a feature as an issue: How to use the example with a different view type (for example UIStackView). I can’t get it to work and it seems to be pretty tight coupled to the tableView.

**Comment by cocodyrockstar** [comment]
i guess u'll just have to replace your tableview with a collectionView (not stackview).
collectionView is also a scrollview like table view.

**Comment by OfTheWolf** [comment]
@gerritwh I updated the repo and now it is possible to add any view. Just create your view controller that extends BottomSheetController and attach to the parrent. that s it. See example project.
